services:
#  client-service:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#    networks:
#      - client-network
#    ports:
#      - "8080:8080"
#    depends_on:
#      - card-db
#      - redis
  client-db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
    networks:
      - client-network
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
    networks:
      - client-network
      - card-network



networks:
  client-network:
  card-network: