server:
  port: 8080

jwt:
  secret: 3bitb3ib5o23b5or23b45or2bohsf83rurhgejfbwkgbvk2lbfkjwjvfjhvvk sfkhjvbkwsvbqbvkjwdbviuwbvowqjdbfiwbfgwiqecbnfowufg
  lifeTime: 1d
spring:
  application:
    name: client-service
  sql:
    init:
      mode: always
  
  datasource:
    url: jdbc:postgresql://client-db:5432/mydatabase
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  data:
    jdbc:
      dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org.springframework.security: debug
