server:
  port: 8080
  sql:
    init:
      mode: always
  servlet:
    context-path: /api/v1
jwt:
  secret: 3bitb3ib5o23b5or23b45or2bohsf8
  lifetime: 30m
spring:
  application:
    name: client-service
  
  datasource:
    url: jdbc:postgresql://client-db:5432/mydatabase
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  data:
    jdbc:
      dialect: org.hibernate.dialect.PostgreSQLDialect