
create table if not exists users(
    id bigint primary key generated by default as identity,
    email varchar unique not null,
    password varchar not null
);
create table if not exists roles(
    id bigint primary key generated by default as identity,
    name varchar unique not null
);

create table if not exists users_roles(
    user_id bigint not null references users(id),
    role_id bigint not null references roles(id),
    primary key (user_id, role_id)
);
