create table users(
    id long primary key generated by default as identity,
    email varchar unique not null,
    password varchar unique not null
);
create table roles(
    id long primary key generated by default as identity,
    name varchar unique not null
);

create table users_roles(
    id_user long not null references users(id),
    id_role long not null references roles(id)
    primary key (id_user, id_role)
);
