create table users(
    id int primary key generated by default as identity,
    email varchar unique not null,
    password varchar unique not null
)

create table user_authorities(
    id int primary key generated by default as identity,
    id_users int not null references users(id),
    authority varchar not null
)