name: Deploy Java App
on:
  workflow_dispatch:
 # push:

jobs:
  test:
    runs-on: ubuntu:latest
    steps:
      - uses: actions/checkout@v4
      - name: Install JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: gradle
      - name: Install dependencies
        run: bash ./gradlew test



